### PR TITLE
add faster solution for 1663

### PR DESCRIPTION
**Pull request by frankegoesdown**

### CODE REVIEW

**Comment by frankegoesdown** [comment]
```
func getSmallestString(n int, k int) string {
	res := make([]rune, n)
	for i := n - 1; i >= 0; i-- {
		diff := k - i
		if diff >= 26 {
			// Need to add z
			res[i] = 'z'
			k = k - 26
		} else {
			res[i] = rune('a' + diff - 1)
			k = k - diff
		}
	}
	return string(res)
}
```
image

```
func getSmallestString1(n int, k int) string {
	if n == 0 {
		return ""
	}
	res, c := "", []byte{}
	findSmallestString(0, n, k, 0, c, &res)
	return res
}

func findSmallestString(value int, length, k, index int, str []byte, res *string) {
	if len(str) == length && value == k {
		tmp := string(str)
		if (*res) == "" {
			*res = tmp
		}
		if tmp < *res && *res != "" {
			*res = tmp
		}
		return
	}
	if len(str) >= index && (*res) != "" && str[index-1] > (*res)[index-1] {
		return
	}
	for j := 0; j < 26; j++ {
		if k-value > (length-len(str))*26 || value > k {
			return
		}
		str = append(str, byte(int('a')+j))
		value += j + 1
		findSmallestString(value, length, k, index+1, str, res)
		str = str[:len(str)-1]
		value -= j + 1

	}
}
```
image

And my solution example:
```
func getSmallestString2(n int, k int) string {
	var result = make([]byte, n)
	for pos := n - 1; pos >= 0; pos-- {
		add := min(k - pos, 26)
		result[pos] = byte(add) + 'a' - 1
		k -= add
	}
	return string(result)
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
```
as you can see it shows more perfomance
image

**Comment by halfrost** [comment]
Thank you for your solution. I optimized your solution again. Like your solution, the solution idea is greed. The time complexity of our solution is the same, both are O(n), and optimization is only constant-level optimization. My solution beats 100%. This is my new code:

image

```go
func getSmallestString(n int, k int) string {
	str, i, j := make([]byte, n), 0, 0
	for i = n - 1; i <= k-26; i, k = i-1, k-26 {
		str[i] = 'z'
	}
	if i >= 0 {
		str[i] = byte('a' + k - 1 - i)
		for ; j < i; j++ {
			str[j] = 'a'
		}
	}
	return string(str)
}
```

**Comment by frankegoesdown** [comment]
Looks great and clean

**Comment by halfrost** [comment]
This solution time complexity is the same with you. Only reduced the number of loops.

**Pull request closed without merging**
