### PR TITLE
Update 3. Longest Substring Without Repeating Characters.go

### PR DESCRIPTION
**Pull request by JessonChan**
improve

### CODE REVIEW

**Comment by yangwenmai** [comment]
please add some improve benchmark result?

**Comment by halfrost** [comment]
Both your commit and original solution time complexity is O(n). I guess these improve means the code is shorter, beacause it doesn't call max() function. @JessonChan

**Comment by JessonChan** [comment]
@halfrost max function will be inlined to function lengthOfLongestSubstring, so it's the same.
@yangwenmai  this pr will reduce loops https://play.golang.org/p/q0M3r1KZbp6

**Comment by halfrost** [comment]
Thanks, wonderful! Your judgment conditions are more excellent. I learned a lot. @JessonChan

**Pull request merged**
